const express=require("express")
const routes=express.Router()
const {getAllNotes,addNote,deleteNote, loginPage,getNavPage ,registerPage,register,login,logout, addNotePage
}=require("../controllers/controllers.js")
routes.get("/allNotes",getAllNotes)
routes.get("/home",getNavPage)
routes.post("/addNote",addNote)
routes.get("/addNote",addNotePage)
routes.delete("/:id",deleteNote)
routes.get("/login",loginPage)
routes.get("/register",registerPage)
routes.post("/register",register)
routes.post("/login",login)
routes.get("/logout",logout)
module.exports={routes}