const express=require("express")
const routes=express.Router()
const {getAllNotes,addNote,deleteNote, loginPage,getNavPage ,registerPage,register,login,logout, addNotePage, forgotPasswordPage, forgotPassword, updatePage, getNote, updateNote,downloadNote,resetPassword,resetUserPassword
}=require("../controllers/controllers.js")
const {authUser}=require("../middlewares/middleware.js")
routes.get("/allNotes",authUser,getAllNotes)
routes.get("/home",authUser,getNavPage)
routes.post("/addNote",authUser,addNote)
routes.get("/addNote",authUser,addNotePage)
routes.delete("/:id",authUser,deleteNote)
routes.get("/",loginPage)
routes.get("/register",registerPage)
routes.post("/register",register)
routes.post("/login",login)
routes.get("/logout",logout)
routes.get("/forgotpassword",forgotPasswordPage)
routes.post("/forgotpassword",forgotPassword)
routes.get("/resetpassword",resetPassword)
routes.post("/resetpassword",resetUserPassword)
routes.get("/update/:id",authUser,updatePage)
routes.get("/note/:id",authUser,getNote)
routes.put("/note/:id",authUser,updateNote)
routes.get("/download/:id",authUser,downloadNote)
module.exports={routes}
